routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/cek', function () {
    return view('lintang');
});
// Route::get('/login2', function () {
//     return view('login2');
// });
Route::get('/firstpage', function () {
    return view('index');
});
Route::get('/', function () {
    return view('welcome');
});

// Route::get('/adminpage', function () {
//     return view('indexadmin');
// });

Route::get('/kelolakoor2', function () {
    return view('indexkelolakoor3');
});

// Route::get('/koorpage', function () {
//     return view('indexkoordinator');
// });
// Route::get('/bentuktim', function () {
//     return view('bentuktim');
// });
Route::get('/mobilisasitim', function () {
    return view('mobilisasitim');
});
// Route::get('/tenagapage', function () {
//     return view('indextenaga');
// });
// Route::get('/lihattim', function () {
//     return view('lihattim');
// });
Route::get('/login2', function () {
    return view('admin.login');
});
Route::get('/login3', function () {
    return view('koordinator.login');
});
// Route::get('/mobilisasi', function () {
//     return view('statusmobilisasi');
// });
// Route::get('/kelolatenaga2', function () {
//     return view('kelolatenaga2');
// });
Route::post('statusmobilisasi','MobilisasitimController@mobilisasi');
Route::get('lihattim','AnggotaController@index');
Route::resource('masuktim','BentukController');
Route::resource('buattim','TimController');
Route::post('cektim','LihattimController@status');
Route::get('cektim','LihattimController@index');
Route::resource('bentuktim','MobilisasiController');

Route::get('statusmobilisasi','MobilisasitimController@index');
Route::post('bentuktim','UserController@inputtim');
Route::resource('user','UserController');
// Route::resource('koordinator','KoordinatorController');
Route::resource('tim','TimController');

//login admin
// Route::resource('/adminpage','AdminController@index');
Route::get('/admin/adminpage','AdminController@index');
Route::get('/admin','AdminController@login');
Route::post('/loginPost','AdminController@loginPost');
Route::get('/logout','AdminController@logout');


//login koordinator
Route::get('/koordinator/koorpage','KoordinatorController@index');
Route::get('/koordinator','KoordinatorController@login');
Route::post('/loginPost2','KoordinatorController@loginPost2');
Route::get('/logout','KoordinatorController@logout');



Auth::routes();
Route::get('home', 'HomeController@index')->name('home');

resources/views/buattim.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">

  <title>Sigap</title>
  <!-- table css -->
  <script type="text/javascript" src="https://ajax.googleapis.com/ajak/libs/
  jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{{ asset('/css/app2.css') }}">

  <link href="css/bootstrap2.min.css" rel="stylesheet" type="text/css">

  <!-- Main CSS -->
  <link rel="stylesheet" href="css/style.css" />
  <!-- Responsive CSS -->
  <link rel="stylesheet" href="css/responsive.css" />

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>


  <!-- Custom styles for this template -->
  <link href="css/creative.min.css" rel="stylesheet">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
</head>

<body>

  <div class="wrapper offcanvas-container" id="offcanvas-container">
    <div class="inner-wrapper offcanvas-pusher">
      <div class="header-cover-home">
        <header>
          <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
              <a class="navbar-brand js-scroll-trigger" href="/adminpage"><br><br><font size="3">SIGAP</font></a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/user"><font size="2">Home</font></a>
                  </li>
                  <li class="nav-item dropdown">
                      <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                      <font size="2">

                       </font>  <span class="caret"></span>
                      </a>

                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{ route('logout') }}"
                             onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                           {{ __('Logout') }}
                          </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>
                      </div>
                  </li>
                <!--  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#services">Services</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
                  </li>-->
                  <!-- <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                  </li> -->
                </ul>
              </div>
            </div>
          </nav>
        </header>

        <section class="slider-section">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <div class="slider">
                  <div class="slideshow-text">
                    <h1>Buat Tim</h1>
                    <p>SISTEM MANAJEMEN TIM KESEHATAN BENCANA</p>
                  </div>
                  <a href="#bootstrap-css" id="go-next" class="go-next"><i class="fa fa-angle-down"></i></a>
                </div> <!-- /slider -->
              </div><!-- /col-md-12 -->
            </div><!-- /row -->
          </div><!-- container-fluid -->
        </section><!-- /slider section -->
      </div> <!-- /header-cover-section -->
</div>
<br><br>
<br><br>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <form method="post" action="{{url('buattim')}}">
    {{csrf_field()}}
    <table style="background-color:white;">
      <tr>
        <td colspan="3" class="row_alert">@if(count($errors) > 0)
  <div class="error">
   <ul>
   @foreach($errors->all() as $error)
    <li>{{$error}}</li>
   @endforeach
   </ul>
  </div>
  @endif
  @if(\Session::has('success'))
  <div class="alert">
   <p>{{ \Session::get('success') }}</p>
  </div>
  @endif
  <br/>
</td>
</tr>
    <tr>
      <td>Nama Tim</td>
      <td>:</td>
      <td><input type="text" name="nama" class="form2"></td>
     </tr>
    <tr>
      <!-- <td>Ketua Tim</td>
        <td>:</td>
        <td><input type="text" name="ketua" class="form2"></td>
      </tr>
      <tr> -->
        <td>Lokasi yang dituju</td>
          <td>:</td>
          <td><input type="text" name="lokasi" class="form2"></td>
        </tr>

        <tr>
          <td>Pos</td>
          <td>:</td>
          <td><input type="text" name="pos" class="form2"></td>
         </tr>
        <div class="form-group row">
          <label for="provinsi" class="col-md-4 col-form-label text-md-right">Provinsi</label>
          <div class="col-lg-8">
          <input list="provinsi" name="provinsi" class="form-control">
          <datalist id="provinsi" >
                  @php

                  $provinsis=DB::table('provinces')->get();

                  @endphp

                  @foreach($provinsis as $provinsi)
                           <option value="{{$provinsi->name}}">
                  @endforeach
          </datalist>
          </div>
        </div>
        <div class="form-group row">
          <label for="kabupaten" class="col-md-4 col-form-label text-md-right">Kabupaten/Kota</label>
          <div class="col-lg-8">
          <input list="kabupaten" name="kabupaten" class="form-control">
          <datalist id="kabupaten" >
                  @php

                  $regencies=DB::table('regencies')->get();

                  @endphp

                  @foreach($regencies as $kabupaten)
                           <option value="{{$kabupaten->name}}">
                  @endforeach
          </datalist>
          </div>
        </div>
        <div class="form-group row">
          <label for="kecamatan" class="col-md-4 col-form-label text-md-right">Kecamatan</label>
          <div class="col-lg-8">
          <input list="kecamatan" name="kecamatan" class="form-control">
          <datalist id="kecamatan" >
                  @php

                  $villages=DB::table('villages')->get();

                  @endphp

                  @foreach($villages as $kecamatan)
                           <option value="{{$kecamatan->name}}">
                  @endforeach
          </datalist>
          </div>
        </div>


      </table>
   <input type="submit" class="button" value="Buat">
</form>




<br><br><br><br>

				<!-- footer-section -->
				<footer class="footer-section">
					<!-- container -->
					<div class="container-fluid">
						<!-- row -->
						<div class="row">
							<div class="col-md-6">
								<div class="copyright-text">
									Copyright &copy; 2018. All Rights Reserved. By KalengKornet					</div><!--  /copyright-text -->
							</div>

						</div><!-- /row -->
					</div><!-- /container -->
				</footer><!-- /footer-section -->





        <!-- Main js -->
    		<script src="js/jquery-1.11.1.min.js"></script>
    		<!-- Modernizr js -->
    		<script src="js/modernizr-2.8.1.min.js"></script>
    		<!-- Bootstrap js -->
    		<script src="js/bootstrap.min.js"></script>
    		<!-- owl.carousel js -->
    		<script src="js/owl.carousel.min.js"></script>
    		<!-- countTo js -->
    		<script src="js/jquery.countTo.js"></script>
    		<!-- stellar js -->
    		<script src="js/stellar.js"></script>
    		<!-- YTPlayer js -->
    		<script src="js/jquery.mb.YTPlayer.js"></script>
    		<script src="js/sidebarEffects.js"></script>
    		<script src="js/classie.js"></script>
    		<!-- smoothscroll js -->
    		<script src="js/smoothscroll.min.js"></script>
    		<!-- viewport js -->
    		<script src="js/jquery.inview.min.js"></script>
    		<!-- Scripts js -->
    		<script src="js/scripts.js"></script>

    		<script src="vendor/jquery/jquery.min.js"></script>
    		<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    		<!-- Plugin JavaScript -->
    		<script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    		<script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    		<script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    		<!-- Custom scripts for this template -->
    		<script src="js/creative.min.js"></script>

<!--===============================================================================================-->
<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/bootstrap2/js/popper.js"></script>
<script src="vendor/bootstrap2/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/daterangepicker/moment.min.js"></script>
<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="js/main.js"></script>
</body>
</html>

resources/views/cektim.blade.php
<!doctype html>

<html>
<head>

  <meta charset="UTF-8">
  <title>Sigap</title>
  <!-- table css -->
  <script type="text/javascript" src="https://ajax.googleapis.com/ajak/libs/
  jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{{ asset('/css/app2.css') }}">

  </script>
  <link href="css/bootstrap2.min.css" rel="stylesheet" type="text/css">

  <!-- Main CSS -->
  <link rel="stylesheet" href="css/style.css" />
  <!-- Responsive CSS -->
  <link rel="stylesheet" href="css/responsive.css" />

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>


  <!-- Custom styles for this template -->
  <link href="css/creative.min.css" rel="stylesheet">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">

</head>

<body>
  <div class="wrapper offcanvas-container" id="offcanvas-container">
    <div class="inner-wrapper offcanvas-pusher">
      <div class="header-cover-home">
        <header>
          <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
              <a class="navbar-brand js-scroll-trigger" href="/koordinator/koorpage"><br><br><font size="3">SIGAP</font></a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/koordinator/koorpage">  <font size="2">Home</font></a>
                  </li>
                  <li class="nav-item dropdown">
                      <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    <font size="2"> Koordinator</font><span class="caret"></span>
                      </a>

                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{ route('logout') }}"
                             onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                              {{ __('Logout') }}
                          </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>
                      </div>
                  </li>
                <!--  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#services">Services</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
                  </li>-->
                  <!-- <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                  </li> -->
                </ul>
              </div>
            </div>
          </nav>
        </header>


        <!-- slider section -->
        <section class="slider-section">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <div class="slider">
                  <div class="slideshow-text">
                    <h1>Mobilisasi Tim</h1>
                    <p>SISTEM MANAJEMEN TIM KESEHATAN BENCANA</p>
                  </div>
                  <!-- <a href="#bootstrap-css" id="go-next" class="go-next"><i class="fa fa-angle-down"></i></a> -->
                </div> <!-- /slider -->
              </div><!-- /col-md-12 -->
            </div><!-- /row -->
          </div><!-- container-fluid -->
        </section><!-- /slider section -->
      </div> <!-- /header-cover-section -->
</div>
<br><br>



<div class="container">
<!-- <h1><b><font  face="Open Sans" size="5">Lihat Tim</font></b></h1> -->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>











@if($message = Session::get('success'))
<div class="success">
	<p>{{$message}}</p>
</div>
@endif
<br/>
<!-- <a href="{{route('user.create')}}" class="button2">Tambah data </a> -->
<br/>

<font size="4" face="Open Sans" >
  <br/><br/>
<table class="table table-striped" style="width: 95%;">
<tr>
	<th>Nama Tim</th>
	<th>Lokasi Tujuan</th>
	<th colspan="2"></th>
</tr>
@foreach($tims as $kelompok)
<tr>
  <td>{{$kelompok['nama']}}</td>
  <td>{{$kelompok['provinsi']}},{{$kelompok['kabupaten']}},{{$kelompok['kecamatan']}},{{$kelompok['pos']}}</td>
 <td class="action"><a  class="btn btn-info" data-toggle="modal" data-target="#tim{{$kelompok['id']}}"><font color="white"> Lihat Anggota </font></a></td>

  <td class="action"><a class="btn btn-primary" data-toggle="modal" data-target="#tim2{{$kelompok['id']}}"> <font color="white">Kerahkan </font></a></td>
</tr>
<!-- anggota modal -->
<div class="modal fade bd-example-modal-lg" id="tim{{$kelompok['id']}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      <div class="modal-header">
      <center>  <h5 class="modal-title" id="exampleModalLongTitle">Anggota Tim</h5></center>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        @php
          $anggotas = DB::table('users')->where('id_tim', $kelompok->id)->get();
          $i = 1;
        @endphp
        @foreach($anggotas as $anggota)
        <div class="table-light">>
        {{$i}}
        {{$anggota->name}}:
        {{$anggota->keahlian}}
        @php $i++; @endphp
        </div>

        @endforeach
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Keluar</button>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- kerahkan modal -->
<div class="modal" id="tim2{{$kelompok['id']}}"  tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Kerahkan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post">
          @csrf
          <div class="">
            Apakah anda yakin ingin mengerahkan tim {{$kelompok['nama']}} ?
          </div>
            <input type="hidden" name="id_tim" value="{{$kelompok->id}}">
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Ya</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
      </form>




      </div>
    </div>
  </div>
</div>


<!-- @foreach($tims as $row)
<tr>
	<td>{{$row['name']}}</td>
	<td>{{$row['tinggal']}}</td>
	<td>{{$row['gender']}}</td>
	<td>{{$row['keahlian']}}</td>
	<td>{{$row['email']}}</td>

	<td class="action"><a href="{{action('UserController@edit',$row['id'])}}" class="btn btn-success"> Edit </a></td>
	<td class="action">
		<form method="post" class="delete_form" action="{{action('UserController@destroy', $row['id'])}}">
      {{csrf_field()}}
      <input type="hidden" name="_method" value="DELETE" />
      <button type="submit" class="btn btn-danger">Delete</button>
     </form>
	</td>
</tr>
@endforeach -->
@endforeach

</table>
</div>

<br><br><br><br>

				<!-- footer-section -->
				<footer class="footer-section">
					<!-- container -->
					<div class="container-fluid">
						<!-- row -->
						<div class="row">
							<div class="col-md-6">
								<div class="copyright-text">
									Copyright &copy; 2018. All Rights Reserved. By KalengKornet					</div><!--  /copyright-text -->
							</div>

						</div><!-- /row -->
					</div><!-- /container -->
				</footer><!-- /footer-section -->



				<!--Video Section Ends Here-->

			<!-- /inner-wrapper -->

		<!-- Main js -->
		<script src="js/jquery-1.11.1.min.js"></script>
		<!-- Modernizr js -->
		<script src="js/modernizr-2.8.1.min.js"></script>
		<!-- Bootstrap js -->
		<script src="js/bootstrap.min.js"></script>
		<!-- owl.carousel js -->
		<script src="js/owl.carousel.min.js"></script>
		<!-- countTo js -->
		<script src="js/jquery.countTo.js"></script>
		<!-- stellar js -->
		<script src="js/stellar.js"></script>
		<!-- YTPlayer js -->
		<script src="js/jquery.mb.YTPlayer.js"></script>
		<script src="js/sidebarEffects.js"></script>
		<script src="js/classie.js"></script>
		<!-- smoothscroll js -->
		<script src="js/smoothscroll.min.js"></script>
		<!-- viewport js -->
		<script src="js/jquery.inview.min.js"></script>
		<!-- Scripts js -->
		<script src="js/scripts.js"></script>

		<script src="vendor/jquery/jquery.min.js"></script>
		<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

		<!-- Plugin JavaScript -->
		<script src="vendor/jquery-easing/jquery.easing.min.js"></script>
		<script src="vendor/scrollreveal/scrollreveal.min.js"></script>
		<script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

		<!-- Custom scripts for this template -->
		<script src="js/creative.min.js"></script>


</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/lintang.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>jQuery Grid Inline Editing</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <table id="grid"></table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            var grid, countries;
            grid = $('#grid').grid({
                dataSource: '/Players/Get',
                uiLibrary: 'bootstrap4',
                primaryKey: 'ID',
                inlineEditing: { mode: 'command' },
                columns: [
                    { field: 'ID', width: 44 },
                    { field: 'Name', editor: true },
                    { field: 'CountryName', title: 'Nationality', type: 'dropdown', editField: 'CountryID', editor: { dataSource: '/Locations/GetCountries', valueField: 'id' } },
                    { field: 'DateOfBirth', type: 'date', editor: true },
                    { field: 'IsActive', title: 'Active?', type: 'checkbox', editor: true, width: 90, align: 'center' }
                ],
                pager: { limit: 5 }
            });
            grid.on('rowDataChanged', function (e, id, record) {
                // Clone the record in new object where you can format the data to format that is supported by the backend.
                var data = $.extend(true, {}, record);
                // Format the date to format that is supported by the backend.
                data.DateOfBirth = gj.core.parseDate(record.DateOfBirth, 'mm/dd/yyyy').toISOString();
                // Post the data to the server
                $.ajax({ url: '/Players/Save', data: { record: data }, method: 'POST' })
                    .fail(function () {
                        alert('Failed to save.');
                    });
            });
            grid.on('rowRemoving', function (e, $row, id, record) {
                if (confirm('Are you sure?')) {
                    $.ajax({ url: '/Players/Delete', data: { id: id }, method: 'POST' })
                        .done(function () {
                            grid.reload();
                        })
                        .fail(function () {
                            alert('Failed to delete.');
                        });
                }
            });
        });
    </script>
</body>
</html>